name: CI

on:
  push:
    branches: [ main, stage, develop ]
  pull_request:
    branches: [ main, stage, develop ]

jobs:
  js-ci:
    uses: wiliest0r/gh-actions-central/.github/workflows/js-tag-ci.yml@main
    with:
      node-version: '24'
      max-gzip-size-kb: 5
