name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag version (e.g. v0.1.0)'
        required: true
        default: 'v0.1.0'

jobs:
  release:
    uses: wiliest0r/gh-actions-central/.github/workflows/release-js-tag.yml@main
    with:
      release-tag: ${{ github.ref_type == 'tag' && github.ref_name || inputs.tag }}
    secrets:
      DISPATCH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
