name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    uses: wiliest0r/gh-actions-central/.github/workflows/release-js-tag.yml@main
    with:
      release-tag: ${{ github.ref_name }}
